# Generated by Django 5.2.6 on 2025-11-28 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregables/%Y/%m/%d/')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('cod_entre', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_entre', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('desc_entre', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'entregable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('cod_eve', models.AutoField(primary_key=True, serialize=False)),
                ('nom_eve', models.CharField(max_length=250)),
                ('fecha_eve', models.DateField(max_length=250)),
                ('desc_eve', models.CharField(max_length=250)),
                ('modalidad_eve', models.CharField(max_length=250)),
                ('direccion_eve', models.CharField(max_length=250)),
                ('estado_eve', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField(max_length=45)),
                ('hora_fin', models.TimeField(max_length=45)),
                ('fecha_estado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoAprendiz',
            fields=[
                ('proapre_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='activo', max_length=10)),
            ],
            options={
                'db_table': 'proyecto_aprendiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemilleroDocumento',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'semillero_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemilleroProyecto',
            fields=[
                ('sempro_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'semillero_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioProyecto',
            fields=[
                ('usupro_id', models.AutoField(primary_key=True, serialize=False)),
                ('es_lider_pro', models.BooleanField(default=False)),
                ('estado', models.CharField(default='activo', max_length=10)),
            ],
            options={
                'db_table': 'usuario_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioUserPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('cod_doc', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_doc', models.CharField(max_length=250)),
                ('fecha_doc', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=250)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
            options={
                'db_table': 'documento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('cod_pro', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=250)),
                ('desc_pro', models.TextField()),
                ('linea_tec', models.CharField(max_length=250)),
                ('linea_inv', models.CharField(max_length=250)),
                ('linea_sem', models.CharField(max_length=250)),
                ('estado_pro', models.CharField(default='diagnostico', max_length=50)),
                ('progreso', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('notas', models.TextField()),
                ('programa_formacion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id_sem', models.AutoField(primary_key=True, serialize=False)),
                ('cod_sem', models.CharField(max_length=20)),
                ('sigla', models.CharField(max_length=250)),
                ('nombre', models.CharField(max_length=250)),
                ('desc_sem', models.TextField()),
                ('objetivo', models.TextField()),
                ('estado', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('progreso_sem', models.IntegerField(default=0)),
                ('proyectos', models.ManyToManyField(blank=True, related_name='semilleros', through='GC2.SemilleroProyecto', to='GC2.proyecto')),
            ],
            options={
                'db_table': 'semillero',
            },
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('cedula_apre', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
                ('ficha', models.IntegerField()),
                ('programa', models.CharField(max_length=100)),
                ('correo_per', models.CharField(max_length=250)),
                ('correo_ins', models.CharField(max_length=250)),
                ('medio_bancario', models.CharField(max_length=45)),
                ('numero_cuenta', models.CharField(max_length=255)),
                ('modalidad', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('estado_apre', models.CharField(max_length=45)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('acepta_tratamiento_datos', models.BooleanField(default=False)),
                ('fecha_aceptacion_datos', models.DateTimeField(blank=True, null=True)),
                ('proyectos', models.ManyToManyField(related_name='aprendices', through='GC2.ProyectoAprendiz', to='GC2.proyecto')),
                ('id_sem', models.ForeignKey(blank=True, db_column='id_sem', null=True, on_delete=django.db.models.deletion.CASCADE, to='GC2.semillero')),
            ],
            options={
                'db_table': 'aprendiz',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SemilleroUsuario',
            fields=[
                ('semusu_id', models.AutoField(primary_key=True, serialize=False)),
                ('es_lider', models.BooleanField(default=False)),
                ('id_sem', models.ForeignKey(db_column='id_sem', on_delete=django.db.models.deletion.CASCADE, to='GC2.semillero')),
            ],
            options={
                'db_table': 'semillero_usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_usu', models.CharField(max_length=250)),
                ('ape_usu', models.CharField(max_length=250)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=250, null=True)),
                ('correo_per', models.CharField(blank=True, max_length=250, null=True)),
                ('correo_ins', models.CharField(max_length=250)),
                ('rol', models.CharField(max_length=250)),
                ('vinculacion_laboral', models.CharField(blank=True, max_length=250, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(max_length=128)),
                ('token_verificacion', models.CharField(blank=True, max_length=250, null=True)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('rol_original', models.CharField(blank=True, max_length=250, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('codigo_expiracion', models.DateTimeField(blank=True, null=True)),
                ('intentos_codigo_fallidos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_codigo_enviado', models.DateTimeField(blank=True, null=True)),
                ('codigos_enviados_hoy', models.IntegerField(default=0)),
                ('fecha_ultimo_reset_codigos', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_usuarios', through='GC2.UsuarioGrupos', to='auth.group')),
                ('proyectos', models.ManyToManyField(related_name='usuarios', through='GC2.UsuarioProyecto', to='GC2.proyecto')),
                ('semilleros', models.ManyToManyField(related_name='usuarios', through='GC2.SemilleroUsuario', to='GC2.semillero')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_usuarios_perms', through='GC2.UsuarioUserPermissions', to='auth.permission')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='semillerousuario',
            name='cedula',
            field=models.ForeignKey(db_column='cedula', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='semillerousuario',
            unique_together={('id_sem', 'cedula')},
        ),
    ]
