# Generated by Django 5.2.7 on 2026-02-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregables/%Y/%m/%d/')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoAprendiz',
            fields=[
                ('proapre_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='activo', max_length=10)),
            ],
            options={
                'db_table': 'proyecto_aprendiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemilleroDocumento',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'semillero_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SemilleroProyecto',
            fields=[
                ('sempro_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'semillero_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioProyecto',
            fields=[
                ('usupro_id', models.AutoField(primary_key=True, serialize=False)),
                ('es_lider_pro', models.BooleanField(default=False)),
                ('estado', models.CharField(default='activo', max_length=10)),
            ],
            options={
                'db_table': 'usuario_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioUserPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_user_permissions',
                'managed': False,
            },
        ),
    ]
