# Generated by Django 5.1.7 on 2025-09-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('cod_doc', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_doc', models.CharField(max_length=250)),
                ('fecha_doc', models.CharField(max_length=250)),
                ('ver_doc', models.IntegerField()),
                ('tipo', models.CharField(max_length=250)),
                ('archivo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('cod_eve', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_eve', models.CharField(max_length=250)),
                ('fecha_eve', models.CharField(max_length=250)),
                ('desc_eve', models.CharField(max_length=250)),
                ('modalidad_eve', models.CharField(max_length=250)),
                ('direccion_eve', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('cod_pro', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=250)),
                ('desc_pro', models.TextField()),
                ('linea_tec', models.CharField(max_length=250)),
                ('linea_inv', models.CharField(max_length=250)),
                ('linea_sem', models.CharField(max_length=250)),
                ('can_entre', models.IntegerField()),
                ('estado_pro', models.CharField(max_length=50)),
                ('cod_form', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('cod_sem', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=250)),
                ('nombre', models.CharField(max_length=250)),
                ('desc_sem', models.TextField()),
                ('objetivo', models.TextField()),
                ('estado', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_usu', models.CharField(max_length=250)),
                ('ape_usu', models.CharField(max_length=250)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, max_length=250, null=True)),
                ('correo_per', models.CharField(blank=True, max_length=250, null=True)),
                ('correo_ins', models.CharField(max_length=250)),
                ('rol', models.CharField(max_length=250)),
                ('vinculacion_laboral', models.CharField(blank=True, max_length=250, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(max_length=250)),
                ('contraseña', models.CharField(max_length=250)),
                ('conf_contraseña', models.CharField(max_length=250)),
                ('token_verificacion', models.CharField(blank=True, max_length=250, null=True)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('imagen_perfil', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('cod_entre', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('nom_entre', models.CharField(max_length=250)),
                ('fecha_entre', models.CharField(max_length=250)),
                ('desc_entre', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=45)),
                ('archivo', models.CharField(max_length=250)),
                ('cod_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC2.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('cedula_apre', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.CharField(max_length=45)),
                ('ficha', models.IntegerField()),
                ('programa', models.CharField(max_length=100)),
                ('correo_per', models.CharField(max_length=250)),
                ('correo_ins', models.CharField(max_length=250)),
                ('medio_bancario', models.CharField(max_length=45)),
                ('numero_cuenta', models.IntegerField()),
                ('modalidad', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('estado_apre', models.CharField(max_length=45)),
                ('cod_sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC2.semillero')),
            ],
        ),
        migrations.CreateModel(
            name='SemilleroDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC2.documento')),
                ('cod_sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC2.semillero')),
            ],
        ),
        migrations.CreateModel(
            name='SemilleroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_eve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC2.evento')),
                ('cod_sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC2.semillero')),
            ],
        ),
        migrations.CreateModel(
            name='SemilleroProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC2.proyecto')),
                ('cod_sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC2.semillero')),
            ],
        ),
        migrations.CreateModel(
            name='SemilleroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC2.semillero')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC2.usuario')),
            ],
        ),
    ]
