# Generated by Django 5.2.7 on 2025-10-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semillerousuario',
            name='es_lider',
            field=models.BooleanField(default=False),
        ),
    ]
