# Generated by Django 5.2.7 on 2025-11-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprendiz',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'managed': True},
        ),
    ]
