# Generated by Django 5.2.7 on 2025-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado_pro',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
