# Generated by Django 5.2.7 on 2025-11-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregable',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='id',
        ),
        migrations.AddField(
            model_name='archivo',
            name='cod_arc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
