# Generated by Django 5.2.7 on 2025-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregables/%Y/%m/%d/')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archivo',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='semillerodocumento',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
