# Generated by Django 5.2.7 on 2025-12-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'managed': True},
        ),
    ]
