# Generated by Django 5.2.7 on 2025-11-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_cuenta',
            field=models.CharField(max_length=255),
        ),
    ]
