# Generated by Django 5.2.7 on 2025-12-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0002_alter_proyecto_estado_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=250, null=True),
        ),
    ]
