# Generated by Django 5.2.7 on 2025-11-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0002_alter_entregable_options_remove_archivo_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
