# Generated by Django 5.2.1 on 2025-11-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0002_alter_aprendiz_numero_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
