# Generated by Django 5.2.7 on 2025-11-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC2', '0003_delete_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregables/%Y/%m/%d/')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('entregable', models.ForeignKey(db_column='cod_entre', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='GC2.entregable')),
            ],
            options={
                'db_table': 'archivo',
                'managed': True,
            },
        ),
    ]
